---
title: "Q5"
author: "Arindom Baruah (32779267)"
format: html
---

## Exercise 5

For each of the following code fragments, write down what a potentially useful null hypothesis and null generating mechanism would be.

:::{.callout-note}
# Question A

`cl` is categorical and `x1` is numeric.

```
ggplot(data) + 
  geom_boxplot(aes(x=cl, y=x1))
```
:::

Answer A

<div class="alert alert-block alert-warning">
$H_o$ : __There is no difference in the distribution of x1 between the levels of cl__.

Null generating mechanism: __Permutation of the cl variable by using the null_permute function__ to generate the required null plot.
</div>

:::{.callout-note}
# Question B
`temp` is the temperature of stars and is thought to have a skewed distribution.

```
ggplot(stars, aes(temp)) +
  geom_histogram()
```
:::
Answer B

<div class="alert alert-block alert-warning">
$H_o$ : __The distribution of the temperature of stars (temp) is a normal distribution__.

Null generating mechanism: __Permutation of the distribution by setting it to "normal" using the null_dist function__.
</div>

:::{.callout-note}
# Question C
`rooms` is an integer variable, `perc` is a percentage (or count/frequency), `miss` is a logical variable indicating the value was missing or not. 

```
ggplot(housing, aes(x=rooms, y=perc, fill = miss)) +
  geom_col(position = "dodge")
```
:::

Answer C

<div class="alert alert-block alert-warning">
$H_o$ : __There is no significant difference in the distribution of percentage for the different rooms between the cases with missing or no missing values__.

Null generating mechanism: __Permutation of the "miss" variable by using the null_permute function__.
</div>

:::{.callout-note}
d. `height` and `weight` are quantitative variables, `sport` is categorical.

```
ggplot(olympics, aes(x = height, 
                     y = weight,  
                     colour = sport)
      ) +
  geom_smooth(method = "lm", se = FALSE)
```

:::

Answer D

<div class="alert alert-block alert-warning">
$H_o$ : __There is no significant linear relationship between height and weight across different sports in the Olympic dataset.__.

Null generating mechanism: __Permutation (null_permute) can be used on the variable "sport" to create null plots for the linear relationship between weight and height of different categories of sports__.
</div>

:::{.callout-note}
e. `.resid` are residuals from a linear model fit.

```
ggplot(housing, aes(sample = .resid)) +
    geom_qq() +
    geom_qq_line() 
```
:::
Answer E

<div class="alert alert-block alert-warning">
$H_o$ : __The residuals in the housing dataset follow a normal distribution__.

Null generating mechanism: __Permutation of the residuals (.resid) by using the null_permute function__.
</div>
